version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - .env
    volumes:
      - ./app:/app
    restart: unless-stopped
