version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: application-portfolio
    container_name: portfolio
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./app:/app
    environment:
      - PORT=${PORT:-5000}
    restart: unless-stopped
