services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: application-portfolio
    container_name: portfolio
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: unless-stopped
