version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: application-portfolio
    container_name: portfolio
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./app:/app
      - ./.env:/app./.env
    environment:
      - PORT=${PORT:-5000}
      - FLASK_ENV=${FLASK_ENV:-production}
    restart: unless-stopped
